class Commands:
    LEECH = "leech@Ttklimz7_RayshaBot"
    PURGE = "purge@Ttklimz7_RayshaBot"
    PAUSEALL = "pausealq@Ttklimz7_RayshaBotl"
    RESUMEALL = "resumeall@Ttklimz7_RayshaBot"
    STATUS = "status@Ttklimz7_RayshaBot"
    SETTINGS = "settings@Ttklimz7_RayshaBot"
    EXEC = "exec@Ttklimz7_RayshaBot"
    UPLOAD = "upload@Ttklimz7_RayshaBot"
    YTDL = "ytdl@Ttklimz7_RayshaBot"
    PYTDL = "pytdl@Ttklimz7_RayshaBot"
    ABOUT = "about@Ttklimz7_RayshaBot"
    GETLOGS = "getlogs@Ttklimz7_RayshaBot"
    SERVER = "server@Ttklimz7_RayshaBot"
    USERSETTINGS = "usetting@Ttklimz7_RayshaBot"
